#pragma once
#include <windows.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.Core.h>
#include <winrt/Windows.UI.Core.h>
#include <winrt/Windows.UI.Composition.h>
#include <winrt/Windows.UI.Input.h>
#include "flutter/ephemeral/flutter_windows.h"
#include "flutter/ephemeral/cpp_client_wrapper/include/flutter/flutter_view_controller.h"
